/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/Home/HeroSection.vue')['default']
    ProjectsSection: typeof import('./src/components/Home/ProjectsSection.vue')['default']
    RandomBg: typeof import('./src/components/Background/RandomBg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsSection: typeof import('./src/components/Home/SkillsSection.vue')['default']
    SocialLinks: typeof import('./src/components/Layout/SocialLinks.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter.vue')['default']
  }
}
