/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    CustomizeTitle: typeof import('./src/components/CustomizeTitle.vue')['default']
    DownloadPage: typeof import('./src/components/pages/DownloadPage.vue')['default']
    HeroSection: typeof import('./src/components/Home/HeroSection.vue')['default']
    LoadingDialog: typeof import('./src/components/LoadingDialog.vue')['default']
    PickStarsHero: typeof import('./src/components/PickStars/PickStarsHero.vue')['default']
    PickStarsList: typeof import('./src/components/PickStars/PickStarsList.vue')['default']
    RandomBg: typeof import('./src/components/Background/RandomBg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteRuntime: typeof import('./src/components/SiteRuntime.vue')['default']
    Skills: typeof import('./src/components/Skills/Skills.vue')['default']
    SkillsHero: typeof import('./src/components/Skills/SkillsHero.vue')['default']
    SkillsProjects: typeof import('./src/components/Skills/SkillsProjects.vue')['default']
    SocialLinks: typeof import('./src/components/Layout/SocialLinks.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter.vue')['default']
    VerticalNav: typeof import('./src/components/VerticalNav.vue')['default']
  }
}
