name: Release Build

on:
  push:
    tags:
      - 'V*'  # 以 V 开头的 tag，例：V1.0.0

permissions:
  contents: write  # 关键：允许写入 Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip dist files
        run: zip -r dist.zip dist

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
